[package]
name = "order-management-example"
version = "0.1.0"
edition = "2021"

[dependencies]
order-management-service-core = { path = "../rust-lib-core/lib" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
chrono = "0.4"
rust_decimal = "1"
env_logger = "0.11"

[workspace]

[patch.crates-io]
teaql-core = { path = "../../../teaql-core" }
teaql-macros = { path = "../../../teaql-macros" }
teaql-runtime = { path = "../../../teaql-runtime" }
teaql-sql = { path = "../../../teaql-sql" }
teaql-data-service = { path = "../../../teaql-data-service" }
teaql-provider-sqlite = { path = "../../../teaql-provider-sqlite" }
