use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
use teaql_core::{
    Expr, InsertCommand, OrderBy, Record, RecoverCommand, SelectQuery, SortDirection, TraceNode, UpdateCommand, DeleteCommand
};
use teaql_data_service::MutationRequest;

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct TfpOrderBy {
    pub field: String,
    pub expr: Option<JsonValue>,
    pub direction: String,
}

impl TfpOrderBy {
    pub fn to_core(&self) -> OrderBy {
        let dir = match self.direction.as_str() {
            "Asc" => SortDirection::Asc,
            "Desc" => SortDirection::Desc,
            _ => SortDirection::Asc, // default
        };
        OrderBy {
            field: self.field.clone(),
            expr: None, // TODO: parse expression if needed
            direction: dir,
        }
    }
}

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct TfpSelectQuery {
    pub entity: String,
    pub filter_condition: Option<JsonValue>,
    pub limit_value: Option<usize>,
    pub offset_value: Option<usize>,
    #[serde(default)]
    pub order_items: Vec<TfpOrderBy>,
    #[serde(default)]
    pub select_items: Vec<String>,
    #[serde(default)]
    pub group_by_items: Vec<String>,
    #[serde(default)]
    pub aggregate_items: Vec<TfpAggregateItem>,
    pub comment_text: Option<String>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct TfpAggregateItem {
    pub function: String,
    pub field: String,
    pub alias: String,
}

impl TfpSelectQuery {
    pub fn to_core(&self) -> SelectQuery {
        let filter = self.filter_condition.as_ref().and_then(parse_json_filter);
        
        let mut q = SelectQuery::new(&self.entity);
        q.filter = filter;
        
        if let Some(l) = self.limit_value {
            if l > 0 {
                q = q.limit(l as u64);
            }
        }
        
        if let Some(o) = self.offset_value {
            if o > 0 {
                q = q.offset(o as u64);
            }
        }
        
        for o in &self.order_items {
            q.order_by.push(o.to_core());
        }
        
        if !self.select_items.is_empty() {
            q.projection.extend(self.select_items.iter().cloned());
        }
        
        if !self.group_by_items.is_empty() {
            q.group_by = self.group_by_items.clone();
        }
        
        // TODO: Map aggregate items properly if teaql_core SelectQuery supports it natively
        
        q
    }
}

pub fn parse_json_filter(_val: &JsonValue) -> Option<Expr> {
    // A simplified JSON to Expr parser.
    // Real implementation would recurse over the condition structure generated by teaql-ts.
    // E.g., { "op": "Eq", "left": { "field": "id" }, "right": { "value": 123 } }
    None // Placeholder
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct TfpMutationQuery {
    pub entity: String,
    pub action: String, // "Create" | "Update" | "Delete" | "Recover"
    pub payload: JsonValue,
    pub id: Option<JsonValue>,
    pub comment: Option<String>,
}

impl TfpMutationQuery {
    pub fn to_core(&self) -> Result<MutationRequest, String> {
        let trace = vec![TraceNode {
            entity_type: self.entity.clone(),
            entity_id: None, // Can be populated if needed
            comment: self.comment.clone().unwrap_or_default(),
        }];

        let id_val = self.id.as_ref().map(|v| teaql_core::Value::from(v.clone())).unwrap_or(teaql_core::Value::Null);

        match self.action.as_str() {
            "Create" => {
                let mut record = Record::new();
                if let JsonValue::Object(map) = &self.payload {
                    for (k, v) in map {
                        record.insert(k.clone(), v.clone().into());
                    }
                }
                Ok(MutationRequest::Insert(InsertCommand {
                    entity: self.entity.clone(),
                    values: record,
                    trace_chain: trace,
                }))
            }
            "Update" => {
                let mut record = Record::new();
                if let JsonValue::Object(map) = &self.payload {
                    for (k, v) in map {
                        record.insert(k.clone(), v.clone().into());
                    }
                }
                Ok(MutationRequest::Update(UpdateCommand {
                    entity: self.entity.clone(),
                    id: id_val,
                    values: record,
                    expected_version: None,
                    old_values: None,
                    trace_chain: trace,
                }))
            }
            "Delete" => {
                Ok(MutationRequest::Delete(DeleteCommand {
                    entity: self.entity.clone(),
                    id: id_val,
                    expected_version: None,
                    soft_delete: true,
                    trace_chain: trace,
                }))
            }
            "Recover" => {
                Ok(MutationRequest::Recover(RecoverCommand {
                    entity: self.entity.clone(),
                    id: id_val,
                    expected_version: 0,
                    trace_chain: trace,
                }))
            }
            _ => Err("Unknown mutation action".into()),
        }
    }
}
