[package]
name = "shared-load-state-example"
version = "0.1.0"
edition = "2021"
publish = false

[features]
inheritance = []

[dependencies]
school_management_service_core = { package = "school-management-service-core", path = "target/generated/lib" }
teaql-core = { path = "../../teaql-core" }
teaql-runtime = { path = "../../teaql-runtime" }
teaql-data-service = { path = "../../teaql-data-service" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[workspace]

[patch.crates-io]
teaql-core = { path = "../../teaql-core" }
teaql-macros = { path = "../../teaql-macros" }
teaql-data-service = { path = "../../teaql-data-service" }
teaql-sql = { path = "../../teaql-sql" }
teaql-runtime = { path = "../../teaql-runtime" }
teaql-provider-sqlite = { path = "../../teaql-provider-sqlite" }
