
[package]
name = "order-management-service-core"
version = "0.1.0"
edition = "2021"
rust-version = "1.80"
description = "Generated TeaQL service crate for order-management-service"
license = "MIT OR Apache-2.0"

[dependencies]
log = "0.4"
chrono = { version = "0.4", features = ["serde"] }
rust_decimal = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
async-stream = "0.3"
futures-util = "0.3"
teaql-core = { path = "../../../../teaql-core" }
teaql-macros = { path = "../../../../teaql-macros" }
teaql-runtime = { path = "../../../../teaql-runtime" }
teaql-sql = { path = "../../../../teaql-sql" }
teaql-data-service = { path = "../../../../teaql-data-service" }
teaql-tool-core = "1.0.0"
teaql-provider-sqlite = { path = "../../../../teaql-provider-sqlite" }
rusqlite = { version = "0.40", features = ["bundled", "chrono", "column_decltype"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
